services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./postgres/config/init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - project-network
    restart: unless-stopped

  auth-service:
    image: youdzhin/auth-service:latest
    container_name: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "80:80"
    networks:
      - project-network
    depends_on:
      - eureka-service


  eureka-service:
    image: youdzhin/sureka-server:latest
    container_name: eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"
    networks:
      - project-network

  api-gateway:
    image: youdzhin/api-gateway:latest
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service
    networks:
      - project-network



networks:
  project-network:
    driver: bridge

volumes:
  postgres: