server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    initial-instance-info-replication-interval-seconds: 10
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka