name: CI - Build Backend

on:
  pull_request:
    branches: [main]
    paths: ['pet-project/**']
  push:           # ← Добавлено
    branches: [main]
    paths: ['pet-project/**']

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: pet_project_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4 # Checkout pull request on closed event
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven' # использовать кеш для повышения производительности
      - name: Build with Maven
        run: mvn -B -ntp package
