name: CD

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: pet_project_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4 # клонировать репозиторий
      - uses: actions/setup-java@v4 #
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven' # использовать кеш для повышения производительности
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Set build id (generate value) # создать уникальный тег на основании времени
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Build Package Push with Maven # собрать проект с новой переменной
        run: mvn -ntp -B verify -Ddocker.version.tag=${{steps.build-number.outputs.BUILD_NUMBER}} jib:build
  deploy-to-vps:
    needs: build  # Ждём успешной сборки и пуша. зависит от успешной job build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 4.tcp.eu.ngrok.io
          port: 13646
          username: evgenijpesko
          password: zena66
          script: |
            echo "Текущая директория: $(pwd)"
            echo "Пользователь: $(whoami)"
            echo "Проверка Docker: $(docker --version || echo 'Docker не установлен')"
            
            # Проверка и установка Docker
            if ! command -v docker &> /dev/null; then
              echo "Установка Docker..."
              # Для macOS используем Homebrew
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
              brew install --cask docker
              open -a Docker  # Запускаем Docker Desktop
              while ! docker info &> /dev/null; do
                echo "Ожидаем запуск Docker..."
                sleep 5
              done
            fi
            
            # Создаем рабочую директорию
            WORK_DIR="$HOME/pet-project"
            mkdir -p "$WORK_DIR"
            cd "$WORK_DIR" || exit 1
            
            # Работа с репозиторием
            if [ ! -d ".git" ]; then
              echo "Клонируем репозиторий..."
              git clone https://${{ secrets.GIT_TOKEN }}@github.com/pet-project.git .
            else
              echo "Обновляем репозиторий..."
              git pull
            fi
            
            # Запуск контейнеров
            docker-compose down || true
            docker-compose pull
            docker-compose up -d