name: CD

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: pet_project_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Set build id
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Build Package Push with Maven
        run: mvn -ntp -B verify -Ddocker.version.tag=${{steps.build-number.outputs.BUILD_NUMBER}} jib:build

  deploy-to-vps:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 4.tcp.eu.ngrok.io
          port: 13646
          username: evgenijpesko
          password: zena66
          script: |
            whoami
            pwd
            git clone https://oauth2:${{ secrets.GIT_TOKEN }}@github.com/Zen-p/pet-project.git
            cd pet-project
            docker compose down -v
            docker compose pull
            docker compose up -d