name: CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: pet_project_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Set build id
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Build Package Push with Maven
        run: mvn -ntp -B verify -Ddocker.version.tag=${{steps.build-number.outputs.BUILD_NUMBER}} jib:build

  deploy-to-vps:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 7.tcp.eu.ngrok.io:17553
          username: evgenijpesko
          password: zena66
          script: |
            whoami
            pwd
            # Диагностика окружения
            echo "Проверка PATH:"
            echo $PATH
            # Добавляем Docker в PATH
            export PATH="/Applications/Docker.app/Contents/Resources/bin:$PATH"
            # Проверяем наличие Docker
            if ! command -v docker &> /dev/null; then
              echo "Ошибка: Docker не найден. Установите Docker Desktop вручную на Mac с помощью 'brew install --cask docker' и запустите его."
              exit 1
            fi
            # Проверяем версию Docker
            docker --version
            # Проверяем наличие docker compose
            if ! docker compose version &> /dev/null; then
              echo "Ошибка: Docker Compose не найден. Убедитесь, что Docker Desktop установлен и запущен."
              exit 1
            fi
            docker compose version
            # Проверяем доступ к домашней директории
            if ! ls -la /Users/evgenijpesko &> /dev/null; then
              echo "Ошибка: SSH не имеет полного доступа к диску. Предоставьте Full Disk Access для 'sshd' и 'Terminal' в System Settings > Privacy & Security > Full Disk Access."
              exit 1
            fi
            echo "Содержимое домашней директории:"
            ls -la /Users/evgenijpesko
            # Клонируем или обновляем репозиторий
            if [ -d "pet-project" ]; then
              echo "Репозиторий уже существует, обновляем..."
              cd pet-project
              git pull origin main
            else
              echo "Клонируем репозиторий..."
              git clone https://oauth2:${{ secrets.GIT_TOKEN }}@github.com/Zen-p/pet-project.git
              cd pet-project
            fi
            # Выполняем команды Docker Compose
            docker compose down -v
            docker compose pull
            docker compose up -d