name: CD

on:
  workflow_dispatch:

jobs:
  deploy-to-vps:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 4.tcp.eu.ngrok.io
          port: 13646
          username: evgenijpesko
          password: zena66
          script: |
            whoami
            pwd
            brew
            docker ps